### ISSUE TITLE
Don't use open-browser-webpack-plugin

### ISSUE THREAD

**Issue by zeusk** [EleanorMao/React-TreeTable#5]
open-browser-webpack-plugin calls xdg-open without checking if it is installed on the system, which fails `npm run dev` because xdg-open fails inside openBrowserPlugin.

Some systems like Windows Subsystem for Linux do not have xdg-open, either as binary or as a buildable target (and it shouldn't, WSL doesn't officially support X server).

**Comment by EleanorMao** [comment]
Okay

**Comment by zeusk** [comment]
Thanks for dbb5078ee493b09b7df6cfb7ed1b0c86766d5b21!
